version = 1

# computer-generated files
[[annotations]]
path = [
	".gitignore",
	".idea/**",
	"pyproject.toml",
	".python-version"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
